### ISSUE TITLE
Feature request: Support for Statamic CMS

### ISSUE THREAD

**Issue by espenlg** [valentinxxx/nginxconfig.io#15]
As I've been thrown into the role as system administrator I was thrilled to find nginxconfig.io to help me out with a rock solid WP config. I would very much like to see a version for the rising Statamic CMS as well. Is there any way that could happen?

**Comment by valentinxxx** [comment]
Hello @espenlg!
I think nginxconfig.io supports Statamic's basic nginx requirements.
If there is something additional please add manually if needed.
