### ISSUE TITLE
Feature request: Proxy for node.js application

### ISSUE THREAD

**Issue by bigvandi** [valentinxxx/nginxconfig.io#16]
Hi. First of all, I must thank you for a great tool.
Did I miss it or there is no functionality for proxying specific ports?

In my case, there is a Node application that works on port 3000 (http://127.0.0.1:3000) and can be accessible from outside, even without Nginx. It would be great to add functionality to generate config for proxying all incoming traffic on port 80 (443) to specific port. Just like that:

    location @server.app {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;

Perhaps it can be done via upstream? Really, I dont know, still new to Nginx:

```
http {
  upstream server.app {
    server 127.0.0.1:3000
}
  server {
    listen 80;
    server_name www.domain.com;
    location / {
      proxy_pass http://server.app 
    }
}
}
```

**Comment by valentinxxx** [comment]
Hello @bigvandi!
Thanks for using nginxconfig.io.
I've deployed the reverse proxy configuration block.
Check it out! 😉

**Comment by bigvandi** [comment]
Wow, that's speed. Thank you!
