### ISSUE TITLE
subdomain redirects to www

### ISSUE THREAD

**Issue by eevahr** [valentinxxx/nginxconfig.io#20]
Excuse me if im missing something here but won't this config always redirect to `www.example.org`, regardless of subdomain?

```nginx
# non-www, subdomains redirect
server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;

        server_name .example.org;

        # SSL
        ssl_certificate /etc/letsencrypt/live/example.org/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/example.org/privkey.pem;
        ssl_trusted_certificate /etc/letsencrypt/live/example.org/fullchain.pem;

        return 301 https://www.example.org$request_uri;
}
```

This is the default if you want both www redirect and a cdn(or any cdn for that matter)
Should it not be `server_name example.org` instead of `.example.org`

**Comment by valentinxxx** [comment]
Hello @eevahr!

Yes this configuration will redirect all `*.example.org` and `example.com` to `www.example.org`.

There is a precedence order:
1. exact name
1. longest wildcard name starting with an asterisk, e.g. “*.example.org”
1. longest wildcard name ending with an asterisk, e.g. “mail.*”
1. first matching regular expression (in order of appearance in a configuration file)

(http://nginx.org/en/docs/http/server_names.html)

So if there is an `example.com` or `cdn.example.org` block defined it should has a higher priority (and the redirection block lower).
