### ISSUE TITLE
Wrong regex in nginxconfig.io/wordpress.conf

### ISSUE THREAD

**Issue by vinaora** [valentinxxx/nginxconfig.io#21]
Please check this regex in **nginxconfig.io/wordpress.conf**

`# WordPress: deny wp-content/plugins nasty stuff 
location ~* ^/wp-content/plugins/.*\.(?!css(\.map)?|js(\.map)?...) {
	deny all;
}`

`/wp-content/plugins/responsive-lightbox/assets/swipebox/css/swipebox.css` --> **ALLOW**
`/wp-content/plugins/responsive-lightbox/assets/swipebox/css/swipebox.min.css` --> **DENY**
`/wp-content/plugins/responsive-lightbox/assets/swipebox/js/jquery.swipebox.js` --> **DENY**
`/wp-content/plugins/responsive-lightbox/assets/swipebox/js/jquery.swipebox.min.js` -->  **DENY**

It means:

`/wp-content/plugins/xxx.{allow_extension}` --> **OK**
`/wp-content/plugins/xxx.yyy.{allow_extension}` --> **Not working**

**Comment by valentinxxx** [comment]
Hello @vinaora!

Thanks for the feedback!

I've replaced the negative lookahead regex with a simple deny location. The asset rules (defined in general.conf) has higher precedence over the plugins directory rule.

Is it works for you now?
