### ISSUE TITLE
Add Support for hhvm 

### ISSUE THREAD

**Issue by ARKKYN** [valentinxxx/nginxconfig.io#24]
Please add support for hhvm and fallback to php-fpm and vice versa

**Comment by ob-jon** [comment]
Addition of PHP-FPM support would be awesome!

**Comment by valentinxxx** [comment]
Hello @ARKKYN!

I've added support for multiple HHVM sockets.

@ob-jon fallbacking to PHP is another challenge 😉

**Comment by ARKKYN** [comment]
Thanks but it still needs fallback for hhvm  when it crashes to fallback to php-fpm

**Comment by valentinxxx** [comment]
Thanks for the example @ARKKYN!
I've deployed the support of the backup PHP server.
