### ISSUE TITLE
Add resolver customization options

### ISSUE THREAD

**Issue by TheBestJohn** [valentinxxx/nginxconfig.io#25]
It would be good to add known, privacy-first DNS lookup options for OCSP Stapling.

i.e 1.1.1.1, 1.0.0.1

**Comment by valentinxxx** [comment]
Hello @TheBestJohn!

Thanks for using [nginxconfig.io](https://nginxconfig.io)!

I've added support for changing OCSP DNS resolvers. The servers are [sorted by performance](https://medium.com/@nykolas.z/dns-resolvers-performance-compared-cloudflare-x-google-x-quad9-x-opendns-149e803734e5).

You find the option at `HTTPS` / `OCSP DNS resolvers`-
