### ISSUE TITLE
Preset switching has issues with order of applying properties

### ISSUE THREAD

**Issue by magebarf** [valentinxxx/nginxconfig.io#28]
When using the "preset" section up top (switching between frontend, backend, Node.js etc.) some properties seems to be applied before the UI has been updated, leading to the new value/setting not registering properly. I noticed this with the Routing tab, connected to the PHP enabled setting.

To easily reproduce, apply either the Frontend or Node.js preset, any one where PHP is not enabled.
Then switch to to a preset where PHP is enabled and the index is index.php, such as backend, Wordpress or Drupal.

At this point PHP becomes enabled, but the index is never set to index.php.

If at this point you click the preset button again, same one again, the index is set to the correct value.

My guess/assumption is that the php setting is applied after the index setting, thus invalidating the new index setting as it tries to apply it before index.php is considered a valid choice.

Attaching a screen recording of the issue.
![nginxconfig](https://user-images.githubusercontent.com/3879511/48627393-c7300c00-e9b4-11e8-8310-fd2afb27d3fc.gif)

**Comment by valentinxxx** [comment]
Thanks for detailed issue!
I've fixed it!
