### ISSUE TITLE
use sites-available not sites-enabled

### ISSUE THREAD

**Issue by Trozz** [valentinxxx/nginxconfig.io#30]
sites-enabled are intended to be symlinked from sites-available, allowing the ability to disable a site without deleting the config.

Details;

Change `/etc/nginx/sites-enabled/example.com.conf` to `/etc/nginx/sites-available/example.com.conf`

Add command `ln -s /etc/nginx/sites-available/example.com.conf /etc/nginx/sites-enabled/example.com.conf`

**Comment by valentinxxx** [comment]
#31 merged.
