### ISSUE TITLE
Python support

### ISSUE THREAD

**Issue by vpoulailleau** [valentinxxx/nginxconfig.io#34]
This website is a very good idea.

I mainly use Python as a backend language (not PHP, have you ever tried Python? ;-) ). To use nginx with Python, the WSGI interface was defined. Do you think that Python support could be added to nginxconfig.io?

Some starting points could be:

 * https://uwsgi-docs.readthedocs.io/en/latest/Nginx.html
 * https://uwsgi-docs.readthedocs.io/en/latest/tutorials/Django_and_nginx.html
 * http://docs.gunicorn.org/en/stable/deploy.html
 * https://www.digitalocean.com/community/tutorials/how-to-serve-flask-applications-with-gunicorn-and-nginx-on-ubuntu-16-04

**Comment by h3ct0rjs** [comment]
It would be a great addition :+1: @valentinxxx

**Comment by 211Lamborghiniexotics** [comment]
Pr0ject z0rg0 is watching y0u

**Comment by Trozz** [comment]
if this is done via a unix socket as in the DO example, you can change the address that is used for proxy_pass under the "Reverse proxy" tab

**Comment by ergoithz** [comment]
> if this is done via a unix socket as in the DO example, you can change the address that is used for proxy_pass under the "Reverse proxy" tab

Wrong, NGINX natively speaks Python's WSGI protocol, no need to proxy HTTP, see http://nginx.org/en/docs/http/ngx_http_uwsgi_module.html

**Comment by Oxicode** [comment]
+1 for python

**Comment by valentinxxx** [comment]
Hello guys! Thanks for the feature request!
I've deployed uWSGI Python support.
Could you please send your feedback?

Is there a "missing asset" fallback required?

**Comment by h3ct0rjs** [comment]
Hi @valentinxxx,  I've checked your last deploy and the options in the live site, it seems okay to me. :smile: 

Thank you very much,
_H_
:+1:
