### ISSUE TITLE
Add a "www" version in "HTTP Redirect" server block

### ISSUE THREAD

**Issue by rafaelfesi** [valentinxxx/nginxconfig.io#39]
The "HTTP Redirect" block is missing a "www.example.com" version of the domain. I've encountered problems on redirecting without it.

````html
server_name .{{ domain() }};<!--
````

It could be something like this: (but is needed to verify if the "www" is checked)
````html
server_name .{{ domain() }} www.{{ domain() }};<!--
````

File: `public/templates/conf/sites-available/example.com.conf.html`
Line: 200

**Comment by valentinxxx** [comment]
According to NGINX docs: http://nginx.org/en/docs/http/server_names.html
**Wildcard names**
`A special wildcard name in the form “.example.org” can be used to match both the exact name “example.org” and the wildcard name “*.example.org”.`
