### ISSUE TITLE
Feature request: add reverse proxy directives

### ISSUE THREAD

**Issue by tobozo** [valentinxxx/nginxconfig.io#4]
and also relevant cache strategies

Also I'll use this issue to say this project is very useful even without this requested feature, I'm bookmarking it and sharing too :)

**Comment by Grafikart** [comment]
I would you imagine this feature working.? What field would you need.and what result would you expect ? (I think I could manage to do the PR for this issue if needed)

**Comment by tobozo** [comment]
It could be a choice between using PHP and reverse proxy I guess since both use the location directive from the root.

Reverse proxy directives can be basic too, the hostname could be editable and maybe a couple of well known options though. But speculating on what's behind the reverse proxy is probably beyond nginxconfig scope.

```
location / {
    proxy_pass       http://localhost:8000;
    proxy_set_header Host      $host;
    proxy_set_header X-Real-IP $remote_addr;
}
```

**Comment by Grafikart** [comment]
I do something like this 

```
  upstream up_{SERVER_NAME} { 
    server {PROXY_URL};
  }

  try_files $uri/index.html $uri @up_{SERVER_NAME}

  location @up_{SERVER_NAME} {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;
    proxy_redirect off;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header X-Forwarded-Proto http;
    proxy_pass http://up_SERVER_NAME;
  }
```

I could do a PR with the "upstream location path" ({PROXY_URL}) being configurable, everything else will be hardcoded in the template. I think the `try_files` approach is better since you can serve static assets with nginx while redirecting everything else to the proxy.

**Comment by valentinxxx** [comment]
Hello @tobozo (and @Grafikart thanks for the input)!
I've deployed the reverse proxy configuration block.
Check it out! 😉

**Comment by tobozo** [comment]
I'm totally impressed :+1: 

btw you can have [multiple values in referrer-policy](https://github.com/w3c/webappsec-referrer-policy/issues/81)
