### ISSUE TITLE
symlink support

### ISSUE THREAD

**Issue by 1271** [valentinxxx/nginxconfig.io#45]
from **/etc/nginx/nginxconfig.io/php_fastcgi.conf**
`fastcgi_param				SCRIPT_FILENAME $document_root$fastcgi_script_name;`
change to
`fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;`
`fastcgi_param DOCUMENT_ROOT $realpath_root;`

Thank.

**Comment by valentinxxx** [comment]
Thanks for the feature request!

I've checked the following resources before implemented it:
- https://serverfault.com/a/848526
- https://hackernoon.com/truly-atomic-deployments-with-nginx-and-php-fpm-aed8a8ac1cd9
