### ISSUE TITLE
Mobile device Redirect

### ISSUE THREAD

**Issue by awsot** [valentinxxx/nginxconfig.io#47]
if access device is mobile ,please  redirect to mobile directory or mobile domain

**Comment by valentinxxx** [comment]
Conditional redirects (user agent) should be handled by your application's business logic.

Also [If Is Evil](https://www.nginx.com/resources/wiki/start/topics/depth/ifisevil/), [nginxconfig.io](https://nginxconfig.io) does not use any `if` in configurations.
