### ISSUE TITLE
Add multiple sites support

### ISSUE THREAD

**Issue by B3DTech** [valentinxxx/nginxconfig.io#5]
Would be great to have a single button support for let's encrypt configuration.

Would also be great to allow multiple site on the same page. Just click add to add another site into the multi-sites config. 

Thanks for this!

**Comment by B3DTech** [comment]
Sorry... Didn't see that let's encrypt is already there!

**Comment by spannerman79** [comment]
Usually it is best practice to close an issue that is no longer an issue @B3DTech

**Comment by B3DTech** [comment]
Second request is still valid though.

**Comment by sewerside** [comment]
please support multiple sites on same domain with SSL for each, I'm having so much issue with this, otherwise your site works really great!!!

**Comment by Jogai** [comment]
For multiple sites its better to use multiple php-fpm pools I think. I used this in the past if you're looking for inspiration: https://github.com/mdPlusPlus/lempstack

**Comment by franzen** [comment]
+1 for supporting multiple virtual hosts

**Comment by Trozz** [comment]
commonly you should create a new virtual host instead of trying to do it all within the same file e.g. add a new file such as `/etc/nginx/sites-enabled/example.com.conf`

**Comment by valentinxxx** [comment]
Thanks guys for the feature request and your inputs!
I'll work on it! 😉

**Comment by kenken1mura** [comment]
delete

**Comment by 211Lamborghiniexotics** [comment]
[pyth0n](url)

**Comment by valentinxxx** [comment]
The implementation of this feature required a huge amount of code re-organization.
I've deployed to this site: https://beta.nginxconfig.io
Could you please review it?
