### ISSUE TITLE
Cannot create directly /vat/www/_letsencrypt

### ISSUE THREAD

**Issue by naviat** [valentinxxx/nginxconfig.io#51]
When I run " # HTTPS - certbot (before first run): create ACME-challenge common directory" 
I got error: "mkdir: cannot create directory ‘/var/www/_letsencrypt’: Permission denied" 
Environment: AWS Ubuntu 18.04

**Comment by EvgeniiProkofev** [comment]
Same for Ubuntu 16.04 in GCE. I have to create directories manually by logging under root.

**Comment by naviat** [comment]
I had to resolved this issue, need to add permission for /var/www
```
sudo gpasswd -a "$USER" www-data
sudo chown -R "$USER":www-data /var/www
find /var/www -type f -exec chmod 0660 {} \;
sudo find /var/www -type d -exec chmod 2770 {} \;
```
