### ISSUE TITLE
Exclude specific path from /\. {deny all}

### ISSUE THREAD

**Issue by EvgeniiProkofev** [valentinxxx/nginxconfig.io#52]
Hi. I am looking for advise. I using TeamCity server behind Nginx reverse proxy. Recently faced a problem when Nginx deny to download zip files from path my-site/some-url/.teamcity/coverage_idea/coverage.zip
My workaround looks like:
`location ~ /\.(?!well-known|teamcity) {
deny all;
}`
But I wish to be more precise. Should I include "allow-block" in reverse-proxy block?

**Comment by valentinxxx** [comment]
Hello @EvgeniiProkofe!
Yes, you should create a location block.
