### ISSUE TITLE
proxy.conf not shown but referenced

### ISSUE THREAD

**Issue by chrisiaut** [valentinxxx/nginxconfig.io#57]
Hello and thanks for this awesome project.

Currently when you select something with a reverse proxy (eg: https://nginxconfig.io/?0.php=false&0.proxy&client_max_body_size=41 ) you get this snipped in your example.com.conf:

```
# reverse proxy
	location / {
		proxy_pass http://127.0.0.1:3000;
		include nginxconfig.io/proxy.conf;
	}
```

But the config file ```include nginxconfig.io/proxy.conf``` is not displayed. Worked a (few) week(s) ago but not anymore.

Also I don't get any JS errors, have enabled and disabled an adblocker and tried it on latest Chrome on Windows and lates Chromium on Linux

**Comment by valentinxxx** [comment]
Thanks @chrisiaut!
I've fixed the issue. 😉

**Comment by chrisiaut** [comment]
wow you're fast :D
