### ISSUE TITLE
Proxied content not transferring images,css,js,audio,video files because of general.conf

### ISSUE THREAD

**Issue by chrisiaut** [valentinxxx/nginxconfig.io#58]
Hello, I had a strange problem and finally figured it out.

# Problem

When I use the configuration to proxy content like with this configuration: https://nginxconfig.io/?0.domain=192.168.1.198&0.https=false&0.php=false&0.proxy&0.proxy_pass=http:%2F%2F192.168.1.119:8080%2F&user=nginx&pid=%2Frun%2Fnginx%2Fnginx.pid&client_max_body_size=100

My page looks like this:

![](https://imgur.com/8D5TqRxl.png)

But when I go to the ```/etc/nginx/nginxconfig.io/general.conf``` and comment out these parts:

```
# assets, media
location ~* \.(?:css(\.map)?|js(\.map)?|jpe?g|png|gif|ico|cur|heic|webp|tiff?|mp3|m4a|aac|ogg|midi?|wav|mp4|mov|webm|mpe?g|avi|ogv|flv|wmv)$
{
        expires 7d;
        access_log off;
}

# svg, fonts
location ~* \.(?:svgz?|ttf|ttc|otf|eot|woff2?)$ {
        add_header Access-Control-Allow-Origin "*";
        expires 7d;
        access_log off;
}
```

then it works

![](https://imgur.com/hsNNsOPl.png)

The reason for this is, that the "location" settings will just be appended to the .conf file of the site.

Which means, if these location blocks **don't also have the proxy pass lines** (which doesn't even work at the moment see #57 ) the site **won't forward** any images,etc.

# Solution 

When user specifies that they want to use a proxy, the cache directives will have to be added to the server block (after the inclusion of general.conf) and will have to include the proxy pass thing. like so:

```
server {
	listen 80;
	listen [::]:80;

	server_name 192.168.1.198;

	# reverse proxy
	location / {
		proxy_pass http://192.168.1.119:8080/;
		include nginxconfig.io/proxy.conf;
	}
    include nginxconfig.io/general.conf;

    # assets, media
    location ~* \.(?:css(\.map)?|js(\.map)?|jpe?g|png|gif|ico|cur|heic|webp|tiff?|mp3|m4a|aac|ogg|midi?|wav|mp4|mov|webm|mpe?g|avi|ogv|flv|wmv)$ {
        expires 7d;
        access_log off;
        proxy_pass http://192.168.1.119:8080/;
        include nginxconfig.io/proxy.conf;
    }

    # svg, fonts
    location ~* \.(?:svgz?|ttf|ttc|otf|eot|woff2?)$ {
        add_header Access-Control-Allow-Origin "*";
        expires 7d;
        access_log off;
        proxy_pass http://192.168.1.119:8080/;
        include nginxconfig.io/proxy.conf;
    }

	
}
```

**Comment by valentinxxx** [comment]
If you disable the `root` directive (under the site configuration, Routing tab), then no asset rules will be generated, so these routes will be passed to the proxy.
