### ISSUE TITLE
ssl_trusted_certificate should point to chain.pem

### ISSUE THREAD

**Issue by Tickthokk** [valentinxxx/nginxconfig.io#59]
Right now the tool points ssl_trusted_certificate to `fullchain.pem`, but I believe it should just point to `chain.pem`.

Reference threads: 
- https://community.letsencrypt.org/t/how-to-set-ssl-trusted-certificate-in-nginx-configuration-file/41898
- https://community.letsencrypt.org/t/i-am-stuck-at-ssl-trusted-certificate/61314

Thank you!

**Comment by valentinxxx** [comment]
Thanks a lot @Tickthokk!
I've changed the code. 😉
