### ISSUE TITLE
Define logs in server block

### ISSUE THREAD

**Issue by spannerman79** [valentinxxx/nginxconfig.io#6]
*If I knew how to do this I would do a PR instead of creating an issue*

When using a separated file structure it is best to define the log path to be specific to that domain.

For example;
```
access_log /var/log/nginx/domain.com_access_log;
error_log /var/log/nginx/domain.com_error_log;
```

Leaving the defaults in ` /etc/nginx/nginx.conf` shouldn't matter but the above should be followed (or very close to it) when doing multi domains for diagnostic purposes.

**Comment by Grafikart** [comment]
What about using the $path instead ? So the user can access his logs

```
access_log $path/logs/access.log;
error_log $path/logs/error.log;
```

Before doing a PR it would be interesting to see if we can agree on where to put the logs ^^

**Comment by spannerman79** [comment]
Yes that seems to be more ideal @Grafikart and perhaps easier in the long run.

**Comment by valentinxxx** [comment]
Hello @spannerman79 and @Grafikart!
I've just updated https://nginxconfig.io with domain specific `access_log` and `error_log`.
Check it out. 😉
