### ISSUE TITLE
Server name missing when Modularized structure is unchecked

### ISSUE THREAD

**Issue by barry-smithjr** [valentinxxx/nginxconfig.io#60]
When creating a new config and unchecking the Modularized structure under common tools section, the server_name, redirect, and ssl_trusted_certificate directives lose the domain. 

          `server {
		listen :443 ssl http2;
		listen []:443 ssl http2;
	
		server_name ;
		set $base /srv/www/domains/domain.com/magento/v230;
		root $base;
	
		# SSL
		ssl_certificate /etc/letsencrypt/live/magento.domain.com/fullchain.pem;
		ssl_certificate_key /etc/letsencrypt/live/magento.domain.com/privkey.pem;
		ssl_trusted_certificate /etc/letsencrypt/live//chain.pem; `

And the redirect server block:

       `# HTTP redirect
	server {
		listen :80;
		listen []:80;
	
		server_name .;
	
		# ACME-challenge
		location ^~ /.well-known/acme-challenge/ {
			root /var/www/_letsencrypt;
		}
	
		location / {
			return 301 https://$request_uri;
		}
	}`

It also appears that the listen port is incorrect and the : is not required for ipv4 and the ipv6 listen should be [::]

**Comment by barry-smithjr** [comment]
Modularized: https://nginxconfig.io/?0.domain=magento.domain.com&0.path=%2Fsrv%2Fwww%2Fdomains%2Fdomain.com%2Fmagento%2Fv230&0.document_root=%2Fpub&0.magento

Non-modularized: https://nginxconfig.io/?0.domain=magento.domain.com&0.path=%2Fsrv%2Fwww%2Fdomains%2Fdomain.com%2Fmagento%2Fv230&0.document_root=%2Fpub&0.magento&file_structure=unified

**Comment by warhost** [comment]
There are actually multiple issues with the non-modularized version. I came across this while trying to configure `api.somedomain.com`.

My config: https://nginxconfig.io/?0.domain=api.domain.com&0.redirect=false&0.http2=false&0.email=domain@domain.com&0.php=false&0.proxy&0.root=false

- `server_name` is empty in the first block.
- `server_name` is just a `.` in the second block.
- `location` for the reverse proxy in the first block is missing the ` / `.
- `proxy_pass` there is empty.
- The `[]` brackets and doublequotes are messed up: `:443 ssl;` and `[]:443 ssl;`, and `listen :80;` and `listen []:80;`.

**Comment by valentinxxx** [comment]
Thank you for the feedback!
I've fixed the issue, could you please check it?
