### ISSUE TITLE
Denying access to WordPress' xmlrpc.php file breaks WP mobile app

### ISSUE THREAD

**Issue by aheckler** [valentinxxx/nginxconfig.io#67]
If nginx denies access to the WordPress xmlrpc.php file, as it does here:

https://github.com/valentinxxx/nginxconfig.io/blob/master/public/templates/conf/nginxconfig.io/wordpress.conf.html#L27

... that will prevent the WP mobile app from connecting to the site properly.

IMHO, that's not something an auto-generated config file should do without at least disclosing it somewhere, or asking the user if they'd like to block it.

**Comment by valentinxxx** [comment]
Good point, but generally speaking a lot of WordPress security related article suggesting it's time to finally disable XML-RPC.
Most of the WordPress based sites don't require the app support.
If you really need it, I advise rename the file (or remove the nginx rule).
