### ISSUE TITLE
Reverse Proxy

### ISSUE THREAD

**Issue by ramaswin121994** [valentinxxx/nginxconfig.io#68]
Unable to set reverse proxy for Jenkins application which is running on 8080 port to example.com/jenkins/

**Comment by valentinxxx** [comment]
What about this config?

https://nginxconfig.io/?0.php=false&0.proxy&0.proxy_path=%2Fjenkins&0.proxy_pass=http:%2F%2F127.0.0.1:8080&0.root=false
