### ISSUE TITLE
Any way to get instructions to install nginxconfig.io on a server

### ISSUE THREAD

**Issue by alexbudin** [valentinxxx/nginxconfig.io#70]
I am working on a system to automate the internal development flow for my team to hook up a new domain in nginx, spin up a digitalocean droplet...etc. All based on a few clicks and inputs.

Any way we can get some instructions on how to install this on a local server?

Thank you.

**Comment by alexbudin** [comment]
Anybody here?

**Comment by valentinxxx** [comment]
Hello @alexbudin!
If you would like to host [nginxconfig.io](https://nginxconfig.io) on your server all you have to do is a git clone and run the following commands:
- `npm install`
- `npm run build:prod`

These commands will create the required assets, after that you have to setup az nginx instance, with the following settings: https://nginxconfig.io/?0.domain=somenginxconfigmirror.com&0.php=false&0.index=index.html&0.fallback_html
