### ISSUE TITLE
"Let's Encrypt e-mail" field is not used

### ISSUE THREAD

**Issue by DanielNagy** [valentinxxx/nginxconfig.io#71]
Using the nginxconfig.io website, the "Let's Encrypt email" field is not parsed to be utilized for the certbot command.

The certbot certonly command appears to stay "info@" whatever domain name is configured in the previous server tab.

**Comment by DanielNagy** [comment]
quick look at template commands.html shows that getDomains() needs to track email as well, and amend the email attribute line to _email rather than data.email

**Comment by valentinxxx** [comment]
Thanks for the feedback!
Fixed. 😉
