### ISSUE TITLE
Every key press, when entering data, pushes new URL to history

### ISSUE THREAD

**Issue by Dainius14** [valentinxxx/nginxconfig.io#77]
When entering data such as domain or path, every key press creates a new history entry in browser's history. URL should be rewritten, but not pushed into history. As you can see, for every key press I got a history entry in my browser (Vivaldi). It's a little irritating. 
![image](https://user-images.githubusercontent.com/15253126/54830648-8c6f1500-4cc1-11e9-8d6b-fc01c72c60ae.png)

**Comment by valentinxxx** [comment]
[nginxconfig.io](https://nginxconfig.io) is using the `$location.search(...).replace()` function https://github.com/valentinxxx/nginxconfig.io/blob/44bbefb38d2f973c956050760c07191cb7ad13fc/public/assets/js/app.js#L304

`replace()` should rewrite the history: https://docs.angularjs.org/api/ng/service/$location#replace.
I've tested in Chrome, Safari and Firefox and works fine.

**Comment by Dainius14** [comment]
It should, but it does not. I've just tested with Firefox 66.0.1 in safe mode and I experience the same behavior.
![image](https://user-images.githubusercontent.com/15253126/54905050-bbb39b00-4ee8-11e9-8f1a-b224e1f3faa7.png)
