### ISSUE TITLE
Security issue with dot files

### ISSUE THREAD

**Issue by spajak** [valentinxxx/nginxconfig.io#88]
With your config it is possible to access and execute `https://www.example.com/.hidden/private.php`
The order of regex locations in nginx IS IMPORTANT. Dot files should be the first regex location in a server config.

**Comment by valentinxxx** [comment]
Thank for your observation!
What do you think about this solution?
```nginx
# . files
location ^~ /. {
	deny all;
}

# .well-known
location ^~ /.well-known/ {
	allow all;
}
```
The longest matching prefix location takes care about precedence.
