### ISSUE TITLE
Mime type for RSS

### ISSUE THREAD

**Issue by xnoreq** [valentinxxx/nginxconfig.io#89]
gzip_types is generated with 'application/xml+rss'

But the right type is 'application/rss+xml'.

**Comment by valentinxxx** [comment]
This is an NGINX related issue.

**Comment by xnoreq** [comment]
> This is an NGINX related issue.

Eh what? NGINX doesn't know what the mime types mean - they are just strings for it, so it has nothing to do with NGINX itself.

**nginxconfig (your project) generates the wrong mime type.** That's the issue here.

**Comment by xnoreq** [comment]
See https://github.com/valentinxxx/nginxconfig.io/blob/178d640647dae870bf0b290a1180701894001bee/public/assets/js/app.js#L356

This line should be:
` $scope.gzipTypes = 'text/plain text/css text/xml application/json application/javascript application/rss+xml application/atom+xml image/svg+xml'; `

**Comment by valentinxxx** [comment]
You're right, sorry. :wink:

**Comment by valentinxxx** [comment]
Btw. nice catch, thanks!
