### ISSUE TITLE
Options to customize open_basedir setting (for symlinks)

### ISSUE THREAD

**Issue by Dannymx** [valentinxxx/nginxconfig.io#90]
So I generated a configuration and I saw this value `fastcgi_param PHP_ADMIN_VALUE	"open_basedir=$base/:/usr/lib/php/:/tmp/";` uses the `$base` to restrict the access for files outside of it.

I also use [Deployer](https://deployer.org/) which generates a `current` directory which contains the public directory, but this directory has a directory symlink'd to the `storage` (for Laravel projects) which resides outside of my `$base`.

Would it be possible to add more options to customize the open_basedir? It would be nice for this to be auto generated here, instead of opening the config file every time.

**Comment by bsormagec** [comment]
you save my life @Dannymx and maintainers killed my 2 hours 😡

**Comment by MattIPv4** [comment]
> maintainers killed my 2 hours 😡

Maintainer here, not sure how we killed your 2 hours? It looks like the original poster here closed the issue themselves... feel free to open a new issue if you'd like to see a feature added. This project is also open-source, so feel free to open a PR to add the feature yourself if you so desire :)
