### ISSUE TITLE
Port 80 server block starts with dot ('.') when subdomain is used

### ISSUE THREAD

**Issue by felix-voicehub** [valentinxxx/nginxconfig.io#92]
Hey, 

check this config out: https://nginxconfig.io/?0.domain=api.example.com

Notice the port 80 server block, the server name is `.api.example.com`, while it should be `api.example.com`.

**Comment by valentinxxx** [comment]
From NGINX docs:

> **server_name**
> Sets names of a virtual server, for example:
``` nginx
server {
    server_name example.com www.example.com;
}
```
> The first name becomes the primary server name.
> &nbsp;
> Server names can include an asterisk (“*”) replacing the first or last part of a name:
```nginx
server {
    server_name example.com *.example.com www.example.*;
}
```
> Such names are called wildcard names.
> &nbsp;
> The first two of the names mentioned above can be combined in one:
```nginx
server {
    server_name .example.com;
}
```

**Comment by felix-voicehub** [comment]
Hm but is that always the case, regardless of the config? E.g. redirect disabled?

**Comment by valentinxxx** [comment]
You mean this case?
https://nginxconfig.io/?0.domain=api.example.com&0.redirect=false

In this case you're probably right, the HTTP block should use only api.example.com as server_name.

**Comment by felix-voicehub** [comment]
Yes I mean this case, I actually forgot to tick that box. This is what I configured yesterday and noticed the extra dot.

**Comment by valentinxxx** [comment]
Thank you! 😉 
Fixed.
